namespace Grimoire.Infrastructure.Export;

using Application.Export;
using Application.Extensions;
using Application.Service.Strategy;
using Common;
using Domain.Entity.Book;
using Epub;
using Microsoft.Extensions.Logging;

public partial class EpubExportStrategy(
    ILogger<EpubExportStrategy> logger,
    ITemplateEngine templateEngine,
    IPackageBuilderFactory packageBuilderFactory) : IExportStrategy {

    public ExportFormat Format => ExportFormat.Epub;

    public async Task<ExportResult> ExportAsync(BookExportContext context) {
        try {
            var builder = packageBuilderFactory.Create();
            var author = context.Series.Metadata?.Authors?.FirstOrDefault();

            builder.SetMetadata(new BookPackageMetadata(
                context.Series.Title,
                author,
                PlainTextDescription: context.PlainTextDescription,
                Tags: context.Series.Metadata?.Tags?.ToList()
            ));

            builder.AddStylesheet(context.Structure.GlobalCss ?? EpubStylesheet.DEFAULT_CSS);

            var coverPath = RegisterCover(context, builder);
            RegisterImages(context, builder);

            var navEntries = BuildSections(context, builder, coverPath, author);
            builder.SetNavigation(navEntries);

            var stream = await builder.BuildAsync();
            var fileName = $"{ExportUtilities.SanitizeFileName(context.Series.Title)}.epub";

            return ExportResult.Ok(stream, fileName, "application/epub+zip");
        }
        catch (Exception ex) {
            LogFailedToExportSeriesIdToEpub(context.Series.Id, ex);
            return ExportResult.Fail(ex.Message);
        }
    }

    /// <summary>
    ///     Adds all pages to the builder and returns the navigation tree.
    ///     nav.xhtml is generated by the builder from this tree — do not add
    ///     it here.
    /// </summary>
    private IReadOnlyList<NavEntry> BuildSections(
        BookExportContext context,
        IPackageBuilder builder,
        string? coverPath,
        string? author) {

        var navEntries = new List<NavEntry>();
        var volumeIndex = 1;
        var chapterIndex = 1;

        foreach (var section in context.Structure.Sections) {
            switch (section.Type) {
                case BookSection.IntroPage or BookSection.Intro: {
                    var html = templateEngine.Render("epub_intro", new {
                        context.Series.Title,
                        Author = author,
                        context.Series.Metadata?.Tags,
                        context.Series.Metadata?.Description,
                        Section = section,
                        CoverLocalPath = coverPath,
                        ImageFileMap = context.AssetFileMap
                    });

                    builder.AddPage("intro", html, PageRole.Intro);
                    navEntries.Add(new NavEntry("intro", EpubConstants.LocalizedText.INTRODUCTION));
                    break;
                }

                case BookSection.Toc or BookSection.TableOfContents: {
                    // Content is generated by the builder from the nav tree.
                    builder.AddPage("toc", string.Empty, PageRole.TableOfContents);
                    navEntries.Add(new NavEntry("toc", EpubConstants.LocalizedText.TABLE_OF_CONTENTS));
                    break;
                }

                case BookSection.Description: {
                    var introSection = context.Structure.Sections
                        .FirstOrDefault(s => s.Type == BookSection.IntroPage);

                    if (introSection == null || ExportUtilities.IsSplitDescriptionEnabled(introSection)) {
                        var html = templateEngine.Render("epub_intro", new {
                            Title = EpubConstants.LocalizedText.SUMMARY,
                            context.Series.Metadata?.Description,
                            Section = section,
                            ImageFileMap = context.AssetFileMap
                        });

                        builder.AddPage("description", html, PageRole.Description);
                        navEntries.Add(new NavEntry("description", EpubConstants.LocalizedText.SUMMARY));
                    }
                    else {
                        LogSkippingSeparateDescriptionSectionIncludedInIntro();
                    }
                    break;
                }

                case BookSection.Content or BookSection.Chapters: {
                    foreach (var volume in context.Volumes) {
                        var volId = $"vol_{volumeIndex++:D3}";
                        var volHtml = templateEngine.Render("epub_volume", new {
                            volume.Title,
                            CoverImagePath = volume.Metadata?.CoverImage != null &&
                                             context.AssetFileMap.TryGetValue(volume.Metadata.CoverImage, out var vp)
                                ? vp
                                : null,
                            volume.Metadata?.PublicationDate,
                            volume.Metadata?.Isbn
                        });

                        builder.AddPage(volId, volHtml, PageRole.VolumeTitle);

                        var chapterEntries = new List<NavEntry>();

                        if (context.ChapterMap.TryGetValue(volume.Id, out var chapters)) {
                            foreach (var chapter in chapters) {
                                var chId = chapter.Id.ToString();
                                var chHtml = templateEngine.Render("epub_chapter", new {
                                    chapter.Title,
                                    chapter.ContentData?.Segments,
                                    chapter.ContentData?.Footnotes,
                                    ImageFileMap = context.AssetFileMap
                                });

                                builder.AddPage(chId, chHtml, PageRole.Chapter);
                                chapterEntries.Add(new NavEntry(chId, chapter.Title));
                                chapterIndex++;
                            }
                        }

                        navEntries.Add(new NavEntry(volId, volume.Title, chapterEntries));
                    }
                    break;
                }

                case BookSection.Unknown:
                    break;
            }
        }

        return navEntries;
    }

    private static string? RegisterCover(BookExportContext context, IPackageBuilder builder) {
        if (context.CoverAsset == null || context.CoverStreamProvider == null) return null;

        var ext = Path.GetExtension(context.CoverAsset.Path)
            .DefaultIfNullOrEmpty(EpubConstants.Defaults.IMAGE_EXTENSION);
        var resolvedFileName = $"cover{ext}";

        builder.AddAsset(resolvedFileName, context.CoverStreamProvider, AssetRefType.Cover);

        // Return the images/-relative path used in templates (epub_intro CoverLocalPath)
        return $"{EpubConstants.Paths.IMAGES_FOLDER}{resolvedFileName}";
    }

    private static void RegisterImages(BookExportContext context, IPackageBuilder builder) {
        foreach (var (assetKey, resolved) in context.ImageAssets) {
            var resolvedFileName = context.AssetFileMap[assetKey];
            builder.AddAsset(resolvedFileName, resolved.StreamProvider, AssetRefType.Content);
        }
    }

    [LoggerMessage(LogLevel.Error, "Failed to export series {SeriesId} to EPUB")]
    partial void LogFailedToExportSeriesIdToEpub(Guid seriesId, Exception exception);

    [LoggerMessage(LogLevel.Information, "Skipping separate description section (included in intro)")]
    partial void LogSkippingSeparateDescriptionSectionIncludedInIntro();
}
